### ISSUE TITLE
投稿一覧ページでコメントも見れるようにする

### ISSUE THREAD

**Issue by zvvlj0219** [StoryEdutech/study_repo#51]

**Comment by enes1004** [comment]
不要です。まず前に出したFBに沿った修正を入れてほしいです。

その次、「特定の投稿を見るページでその投稿のコメントが見れる・追加できる」、ということをしてほしいです。

一旦閉じます。

**Comment by enes1004** [comment]
@zvvlj0219 
こちら、確認できたら新しいIssue作って、
 - #50 
に記載するか、Issue名/内容を編集して、Reopenするかでお願いします
