### ISSUE TITLE
【武井・6/5(月)・6/16(金)】～Next App Routerによる記事投稿サイトの作成～ 

### ISSUE THREAD

**Issue by mokupon** [StoryEdutech/study_repo#59]
### 内容

今回参照するページ：https://zenn.dev/azukiazusa/articles/next-js-app-dir-tutorial

- [x] #64
- [x] #66
- [x] #72
- [x] #77

### FB担当者

エネス

### 内容設計の現況

- [X] 内容書き込み済み（＝WIPじゃない）
- [x] FB者が内容に承諾済み

**Comment by mokupon** [comment]
@enes1004 

### 相談内容
今回のエネスさんがリンクを出していただいた、[こちら](https://zenn.dev/azukiazusa/articles/next-js-app-dir-tutorial)ですが、全ての内容を一通り進めるとしたら、何時間で完了すると見積もっているでしょうか、？

現時点での武井の認識では記事をざっと全て見て、15時間×1.5倍(バッファ)で22.5時間で完了すると見積もっています。

**Comment by mokupon** [comment]
申し訳ございません。画面仕様書の遅れで、そちらを優先したことで、こちら16日(金)までにさせていただきます。
この日にはPR出しが完了しているという状態にします。
よろしくお願い致します。

**Comment by enes1004** [comment]
@mokupon 
記事の作成あたり、コスパ悪そうなので、1時間でOKです！(木下にも同じように言ってます)
