### ISSUE TITLE
【木下・6/5 ・6/9】記事投稿サイト作成

### ISSUE THREAD

**Issue by zvvlj0219** [StoryEdutech/study_repo#60]
### 内容

- [x] #61
- [x] #65
- [x] #69
- [x] #71
- [x] #75
- [x] #78

### FB担当者

エネス

### 内容設計の現況

- [X] 内容書き込み済み（＝WIPじゃない）
- [x] FB者が内容に承諾済み

**Comment by enes1004** [comment]
ベター要件で、それぞれに割く時間も記載していいと思います！

**Comment by enes1004** [comment]
記事の作成あたり、コスパ悪そうなので、1時間でOKです！

**Comment by zvvlj0219** [comment]
終了したのでクローズします
